abbrevs:
  # git
  - name: git
    abbr: g
    snippet: git
  - name: git commit
    abbr: c
    snippet: commit
    global: true
    context: '^git\s'
  - name: git commit -m
    abbr: cm
    snippet: 'commit -m'
    global: true
    context: '^git\s'
  - name: git add
    abbr: a
    snippet: 'add'
    global: true
    context: '^git\s'
  - name: git status
    abbr: s
    snippet: 'status'
    global: true
    context: '^git\s'
  - name: git diff
    abbr: d
    snippet: 'diff'
    global: true
    context: '^git\s'
  - name: git pull
    abbr: pl
    snippet: 'pull'
    global: true
    context: '^git\s'
  - name: git push
    abbr: ps
    snippet: 'push'
    global: true
    context: '^git\s'

