abbrevs:
  - name: open something with wsl
    abbr: open
    snippet: '/mnt/c/Windows/System32/rundll32.exe url.dll,FileProtocolHandler'
    # WSLの場合のみ有効
    if: '[[ $(uname -r) == *"microsoft"* ]]'
  - name: wget with hsts
    abbr: wget
    snippet: 'wget --hsts-file $XDG_STATE_HOME/wget/.wget-hsts'
  - name: terraform
    abbr: tf
    snippet: terraform
  - name: list $PATH
    abbr: echo-path
    snippet: 'echo $PATH | sed "s/:/\n/g"'
  - name: list $FPATH
    abbr: echo-fpath
    snippet: 'echo $FPATH | sed "s/:/\n/g"'
  # chezmoi
  - name: chezmoi
    abbr: cz
    snippet: chezmoi
  - name: chezmoi add
    abbr: a
    snippet: 'add'
    global: true
    context: '^chezmoi\s'
  - name: chezmoi edit
    abbr: e
    snippet: 'edit'
    global: true
    context: '^chezmoi\s'
  - name: chezmoi diff
    abbr: d
    snippet: 'diff'
    global: true
    context: '^chezmoi\s'
  - name: chezmoi cd (replace)
    abbr: cd-c
    snippet: cd $(chezmoi source-path)
  # git
  - name: git
    abbr: g
    snippet: git
  - name: git commit
    abbr: c
    snippet: commit
    global: true
    context: '^git\s'
  - name: git commit -m
    abbr: cm
    snippet: 'commit -m'
    global: true
    context: '^git\s'
  - name: git commit --amend
    abbr: ca
    snippet: 'commit --amend'
    global: true
    context: '^git\s'
  - name: git add
    abbr: a
    snippet: 'add'
    global: true
    context: '^git\s'
  - name: git status
    abbr: s
    snippet: 'status'
    global: true
    context: '^git\s'
  - name: git diff
    abbr: d
    snippet: 'diff'
    global: true
    context: '^git\s'
  - name: git pull
    abbr: pl
    snippet: 'pull'
    global: true
    context: '^git\s'
  - name: git push
    abbr: ps
    snippet: 'push'
    global: true
    context: '^git\s'
  - name: git log
    abbr: l
    snippet: 'log'
    global: true
    context: '^git\s'
  - name: git branch
    abbr: b
    snippet: 'branch'
    global: true
    context: '^git\s'
  - name: git switch
    abbr: sw
    snippet: 'switch'
    global: true
    context: '^git\s'
  - name: cd to ghq repo dir
    abbr: cd-g
    snippet: 'cd $(ghq root)/$(ghq list | fzf)'
  - name: cd to root dir on git repo
    abbr: cd-gr
    snippet: 'cd $(git rev-parse --show-toplevel)'
  # replacements
  - name: ls -> eza
    abbr: ls
    snippet: eza
  - name: cat -> bat
    abbr: cat
    snippet: bat
  - name: find -> fd
    abbr: find
    snippet: fd
  - name: grep -> rg
    abbr: grep
    snippet: rg
  - name: tmux -> zellij
    abbr: tmux
    snippet: zellij
  - name: tmux -> zellij
    abbr: tm
    snippet: zellij

