# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

[plugins.rust-zsh-completions]
github = "ryutok/rust-zsh-completions"
apply = [ 'defer' ]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = [ 'defer' ]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = [ 'defer' ]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = [ 'defer' ]

[plugins.history-search-multi-word]
github = "zdharma-continuum/history-search-multi-word"
apply = [ 'defer' ]

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit -d "${XDG_DATA_HOME}/zcompdump"'

[plugins.p10k]
inline = 'source "${XDG_CONFIG_HOME}/zsh/.p10k.zsh"'

[plugins.p10k-instant-prompt]
inline = '[ -f "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh" ] && source "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh"'

[plugins.enhancd]
github = "b4b4r07/enhancd"
apply = [ 'defer' ]

[plugins.direnv]
local = "~/.local/share/gh-rd/packages/github.com/direnv/direnv"
apply = [ 'defer', 'source' ]

[plugins.zabrze]
local = "~/.local/share/gh-rd/packages/github.com/Ryooooooga/zabrze"
apply = [ 'defer', 'source' ]

[plugins.custom-fn]
inline = 'zsh-defer source "${XDG_CONFIG_HOME}/zsh/.custom-fn.zsh"'
