[tools]
"github:rossmacarthur/sheldon" = "0.8.5"
gh = "2.97.0"
"github:sharkdp/bat" = "0.26.1"
"github:bitwarden/clients" = { version = "2026.7.0", version_prefix = "cli-v", matching_regex = "^bw-(linux|macos|windows)(-arm64)?-" }
cargo-make = "0.37.24"
"cargo:jj-starship" = "0.7.1"
"cargo:zabrze" = "0.7.3"
"github:eza-community/eza" = "0.23.5"
"github:sharkdp/fd" = "10.4.2"
"github:junegunn/fzf" = "0.74.3"
"github:x-motemen/ghq" = "1.10.1"
go = "1.27.0"
"github:jj-vcs/jj" = "0.44.0"
node = "24.19.0"
"github:BurntSushi/ripgrep" = "15.2.0"
"github:starship/starship" = "1.26.0"
terraform = "1.15.9"
usage = "5.1.0"
uv = "0.12.5"
yq = "4.53.6"
"github:zellij-org/zellij" = "0.45.0"
doppler = { version = "3.76.5", exe = "doppler" }
"github:gitleaks/gitleaks" = "8.30.1"
"jjui" = "0.10.9"
"npm:@openai/codex" = "0.148.0"
kustomize = "5.8.1"
"go:github.com/koki-develop/ghasec" = "0.17.0"
shellcheck = "0.11.0"
"github:Lucky3028/cos" = "1.0.5"

[hooks]
postinstall = "$MISE_CONFIG_HOME/hooks/postinstall.sh"
# Set GIT_DIR in jj repo
cd = '''
unset GIT_DIR
if jj root > /dev/null 2>&1; then
  export GIT_DIR=$(jj git root)
fi
'''

[settings]
idiomatic_version_file_enable_tools = ["java"]
experimental = true
