name: Check GitHub Actions security
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
permissions: {}
jobs:
  ghasec:
    name: Run ghasec
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: koki-develop/ghasec-action@2810775d2a300cb3fd9583c36c05b5ee3310c5b8 # v1.1.1
        with:
          version: v0.17.0
          install-shellcheck: true
