name: Lint and format shell files
on:
  pull_request:
    branches:
      - main
jobs:
  shellcheck:
    name: Run shellcheck
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: reviewdog/action-shellcheck@ccaafec0e6d1da9d10f6a97b8ab4a4e8568f7375 # v1.31.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          # warning以上の問題が検出された場合にCIを失敗させる（info のみの場合はCIは成功）
          fail_level: warning
  shfmt:
    name: Run shfmt
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: reviewdog/action-shfmt@d8f080930b9be5847b4f97e9f4122b81a82aaeac # v1.0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: warning
