name: Format shell files
on:
  pull_request:
    branches:
      - main
permissions: {}
jobs:
  shfmt:
    name: Run shfmt
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: reviewdog/action-shfmt@c5e3ba7497c338866921924691aef4fa18bc1fe0 # v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_level: warning
          shfmt_flags: -i 2
