name: Validate Renovate config
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/renovate.json5
      - .github/workflows/validate-renovate-config.yaml
  push:
    branches:
      - main
    paths:
      - .github/renovate.json5
      - .github/workflows/validate-renovate-config.yaml
permissions: {}
jobs:
  validate:
    name: Validate Renovate config
    runs-on: ubuntu-26.04
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@b850926b611b1f3d3fe3729776339c217834bf2c # v2.2.0
